DB = "nr_ncbi" #nr.gz database, downloaded May 10, 2018
SPECIES = ["Amel","Mphar"] #Protein fasta files have headers edited, according to AlexGa github (note that need to remove "cellular organisms")

rule all:
	input: expand("blastALL_{species}_final_ps_map.csv",species=SPECIES)

rule makeDB:
	output: "nr_ncbi.00.phr"
	shell: "makeblastdb -dbtype prot -in {DB}"

rule psMap:
	input: "nr_ncbi.00.phr",
			genomes="test_species/{species}_edit.fa",
	output: "blastALL_{species}_final_ps_map.csv"
	shell: "perl createPSmap.pl --organism {input[genomes]} --database {DB} --prefix blastALL_{wildcards.species} --threads 80 --blastPlus"


